dist: bionic
branches:
  only:
    - master
    - "/(^hotfix-\\d+\\.\\d+(\\.\\d+)?$)|(^\\d+\\.\\d+\\.\\d+$)/"
language: scala
jdk: openjdk12
scala:
  - 2.12.11
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
env:
  global:
    - DOCKER_LABEL=$TRAVIS_BRANCH
    - DOCKER_PUSH_LATEST=true
    - DOCKER_REPOSITORY=renku/
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.8.2-linux-amd64.tar.gz
    - SBT_OPTS="-XX:+CMSClassUnloadingEnabled -Xmx1G"
  matrix:
    - secure: mTY6uy3qD/3L98jz010e3hb/C8ozy+HkRKfYGi5C82hNJY4nWtXvZh/C6fG2d3Dv5Ep3WYdRowc4526B+RWWTIS/DCwQLJrxwQzQ7DwivvqJsCgC/iiqyISsFZT6xNYKDgSbgKhTWgzWJezkXYTRFIRcbqYu9GNs/pcZRwjs7htKbGCUJg9hAYoEkSbX6z4UA0VGEYZx6IskHDEGSNkhQOFELzZEQjW2ChRulBIAjCQ17JnFnL/HNWK8ON9Dy6GR/oZGtLUb3iVYynlPpgFhPJhWsw4/rkuIpqu5ehE0CLxbGKvy8vDaOjRrvWOvI2RA8kV4raPbzLRRkVcl10fIxzZqFO+GRObh0xDtU1kEEVF3ft4EiYNqmCHWPRUR1qN1rTUzrGQpHImnSnoq3ijo0dh9bCjNAjzoHf6Uz7YzbVfoFx6g1adqoDHRi10DdKSqukamiIjo+uT8RKcpzVJfSQ1QpQWyqYJ5gJZltgxwe0XQm0p3gJTyKdjYiK7yfzfqvwMa1sBVBmJ0/9yubUBr22zd6SHvS4AGZIozJNPdfHBKkQc0KRD0Lt6GCQpxVdKJs3SQG8m4wDZGvzVWkb7faYGlk3AOJ7qdbgnAyWZHLVXx2z8PLkF/oU8GWvX+Oy/R/5/qJIqUrjBl0mjSG34gGB9Bex0hS7hnclDxgmFcl8o=
git:
  depth: false
addons:
  apt:
    packages:
      - python3
      - python3-pip
before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update
install:
  - travis_retry sudo pip3 install -U pip
  - travis_retry sudo pip3 install "docker==4.2.2" "chartpress==0.6.0" "ruamel.yaml==0.15.54"
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dsbt.color=always -Dsbt.supershell=false clean test && sbt ++$TRAVIS_SCALA_VERSION  -Dsbt.color=always -Dsbt.supershell=false "project acceptance-tests" clean test && bash ./.travis/check-code-formatting.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./.travis/travis-release.sh
    on:
      branch: master
      repo: SwissDataScienceCenter/renku-graph
  - provider: script
    skip_cleanup: true
    script: bash ./.travis/travis-publish.sh
    on:
      tags: true
      repo: SwissDataScienceCenter/renku-graph
  - provider: script
    skip_cleanup: true
    script: bash ./.travis/travis-hotfix.sh
    on:
      all_branches: true
      repo: SwissDataScienceCenter/renku-graph
