dist: xenial
branches:
  only:
  - master
language: scala
jdk: openjdk8
scala:
- 2.12.8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
env:
  global:
    - DOCKER_LABEL=$TRAVIS_BRANCH
    - DOCKER_PUSH_LATEST=true
    - DOCKER_REPOSITORY=renku/
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.8.2-linux-amd64.tar.gz
    - SBT_OPTS="-XX:+CMSClassUnloadingEnabled -Xmx1G"
git:
  depth: false
addons:
  apt:
    packages:
      - python3
      - python3-pip
before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update
  - sudo apt-get install python3.6 -y
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
  - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
install:
  - travis_retry sudo pip3 install -U pip
  - travis_retry sudo pip3 install "chartpress>=0.2.1" "ruamel.yaml==0.15.54"
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
script:
- sbt ++$TRAVIS_SCALA_VERSION clean test && bash ./.travis/check-code-formatting.sh
deploy:
  - &script
    provider: script
    skip_cleanup: true
    script: bash ./.travis/travis-deploy.sh
    on: &script_on
      branch: master
      repo: SwissDataScienceCenter/renku-graph
  - <<: *script
    on:
      <<: *script_on
      tags: true
