apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jena.fullname" . }}
  labels:
    app: {{ template "jena.name" . }}
    chart: {{ template "jena.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  jena-admin-password: {{ required "Fill in .Values.jena.admin.password with `openssl rand -hex 16`" .Values.jena.admin.password | b64enc | quote }}
