---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-entrypoint-sh
  labels:
    app: {{ template "jena.name" . }}
    chart: {{ template "jena.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  docker-entrypoint.sh: |-
    #!/bin/sh

    SERVER_START=$FUSEKI_BASE/fuseki-server.sh
    exec $SERVER_START
