---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fuseki-server-sh
  labels:
    app: {{ template "jena.name" . }}
    chart: {{ template "jena.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fuseki-server.sh: |-
    #!/bin/sh

    JAVA=$JAVA_HOME/bin/java
    JAR=$FUSEKI_HOME/fuseki-server.jar
    ATTEMPT=1

    wait_for_db_folder () {
      if [ ! -d "$FUSEKI_BASE/databases/{{ .Values.global.graph.jena.dataset }}" ];
      then
        if [ "$ATTEMPT" -lt "6" ]
        then
          ATTEMPT=$((ATTEMPT + 1))
          sleep 5s
          echo $FUSEKI_BASE/databases/{{ .Values.global.graph.jena.dataset }} doesn't exist
          wait_for_db_folder
        fi
      fi
    }

    echo Waiting for mount points...
    wait_for_db_folder

    echo Preparing for Lucene indices rebuilding...
    # killing Jena if already started as Lucene indexing cannot happen on started Jena
    killall -9 java
    rm $FUSEKI_BASE/databases/{{ .Values.global.graph.jena.dataset }}/tdb.lock
    rm $FUSEKI_BASE/system/tdb.lock

    echo Rebuilding Lucene indices...
    DATASET_CONFIG=$FUSEKI_BASE/configuration/{{ .Values.global.graph.jena.dataset }}.ttl
    $JAVA -Xmx2G -cp $JAR jena.textindexer --desc=$DATASET_CONFIG

    echo Starting Fuseki...
    $JAVA $JVM_ARGS $JAVA_OPTS -jar $JAR "$@"
