---
apiVersion: v1
kind: Secret
metadata:
  name: jena-shiro-ini
  labels:
    app: {{ template "jena.name" . }}
    chart: {{ template "jena.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  shiro.ini: |-
    [main]
    # Development
    ssl.enabled = false

    plainMatcher=org.apache.shiro.authc.credential.SimpleCredentialsMatcher
    iniRealm.credentialsMatcher = $plainMatcher

    [users]
    admin={{ .Values.admin.password }}
    renku={{ .Values.renku.password }}

    [roles]

    [urls]
    ## Control functions open to anyone
    /$/status = anon
    /$/ping   = anon

    ## and the rest are restricted
    /$/** = authcBasic,user[admin]
    /{{ .Values.global.graph.jena.dataset }}/** = authcBasic,user[renku]
