apiVersion: v1
kind: Secret
metadata:
  name: client-certificate-secret
  labels:
    app: renku-graph
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ if not .Values.global.clientCertificate }}
  client-certificate: ""
{{ else }}
  client-certificate: {{ default ("") .Values.global.clientCertificate.value | b64enc | quote }}
{{ end }}
