apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "graph-services.fullname" . }}
  labels:
    app: {{ template "graph-services.name" . }}
    chart: {{ template "graph-services.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "graph-services.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "graph-services.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-triples-generator
          image: "{{ .Values.triplesGenerator.image.repository }}:{{ .Values.triplesGenerator.image.tag }}"
          imagePullPolicy: {{ .Values.triplesGenerator.image.pullPolicy }}
          env:
            - name: FILE_EVENT_LOG_PATH
              value: /events/log.txt
            - name: PLAY_APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "graph-services.fullname" . }}
                  key: triplesGenerator-play-secret
            - name: GITLAB_BASE_URL
              value: {{ .Values.gitlab.url }}
            - name: JENA_BASE_URL
              value: "http://{{ include "call-nested" (list . "jena" "jena.fullname") }}:{{ .Values.jena.service.port }}"
            - name: JENA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "call-nested" (list . "jena" "jena.fullname") }}
                  key: jena-admin-password
          ports:
            - name: http1
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http1
          readinessProbe:
            httpGet:
              path: /ping
              port: http1
          volumeMounts:
          - name: file-event-log
            mountPath: /events
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: {{ .Chart.Name }}-webhook-service
          image: "{{ .Values.webhookService.image.repository }}:{{ .Values.webhookService.image.tag }}"
          imagePullPolicy: {{ .Values.webhookService.image.pullPolicy }}
          env:
            - name: FILE_EVENT_LOG_PATH
              value: /events/log.txt
            - name: PLAY_APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "graph-services.fullname" . }}
                  key: webhookService-play-secret
            - name: GITLAB_BASE_URL
              value: {{ .Values.gitlab.url }}
          command:
            - bin/webhook-service
            - -Dhttp.port=9001
          ports:
            - name: http2
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http2
          readinessProbe:
            httpGet:
              path: /ping
              port: http2
          volumeMounts:
          - name: file-event-log
            mountPath: /events
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: file-event-log
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "graph-services.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
