{{- if not .Values.global.graph.eventLog.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eventLog.fullname" . }}-postgres
  labels:
    app: {{ template "eventLog.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ if or .Values.global.graph.dbEventLog.postgresPassword.value .Values.global.graph.dbEventLog.postgresPassword.overwriteOnHelmUpgrade -}}
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
    {{- else -}}
    "helm.sh/hook": "pre-install,pre-rollback"
    {{- end }}
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  graph-eventLog-postgresPassword: {{ default (randAlphaNum 64) .Values.global.graph.dbEventLog.postgresPassword.value | b64enc | quote }}
{{- end }}
