apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "graphService.fullname" . }}
  labels:
    app: {{ template "graphService.name" . }}
    chart: {{ template "graphService.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "graphService.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "graphService.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: graph-service
          image: "{{ .Values.graphService.image.repository }}:{{ .Values.graphService.image.tag }}"
          imagePullPolicy: {{ .Values.graphService.image.pullPolicy }}
          env:
            - name: JENA_DATASET_NAME
              {{- if .Values.global.graph.jena.dataset }}
              value: {{ .Values.global.graph.jena.dataset }}
              {{- else }}
              value: {{ .Release.Namespace }}
             {{- end }}
            - name: JENA_BASE_URL
              value: "http://{{ template "jena.fullname" . }}:{{ .Values.jena.service.port }}"
            - name: RENKU_BASE_URL
              value: {{ .Values.graphService.services.renku.url }}
            - name: JENA_RENKU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jena.fullname" . }}
                  key: jena-renku-password
            - name: SENTRY_DSN
              value: {{ .Values.sentry.sentryDsnRenkuGraph }}?stacktrace.app.packages=&servername=graph-service&environment={{ .Release.Namespace }}
            - name: THREADS_NUMBER
              value: "{{ .Values.graphService.threadsNumber }}"
            - name: JAVA_OPTS
              value: -Xmx200m -XX:+UseG1GC
          ports:
            - name: http-graph-sv
              containerPort: 9004
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http-graph-sv
          readinessProbe:
            httpGet:
              path: /ping
              port: http-graph-sv
          resources:
{{ toYaml .Values.graphService.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
