apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jena.fullname" . }}
  labels:
    {{- include "jena.labels" . | nindent 4 }}
type: Opaque
data:
  jena-users-admin-password: {{ required "Fill in .Values.jena.users.admin.password with `openssl rand -hex 16|base64`" .Values.jena.users.admin.password | b64enc | quote }}
  jena-users-renku-password: {{ required "Fill in .Values.jena.users.renku.password with `openssl rand -hex 16|base64`" .Values.jena.users.renku.password | b64enc | quote }}
