apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowledgeGraph.fullname" . }}
  labels:
    app: {{ template "knowledgeGraph.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "knowledgeGraph.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "knowledgeGraph.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: {{ .Values.global.debug }}
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
      containers:
        - name: knowledge-graph
          image: "{{ .Values.knowledgeGraph.image.repository }}:{{ .Values.knowledgeGraph.image.tag }}"
          imagePullPolicy: {{ .Values.knowledgeGraph.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: RENKU_CLIENT_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: client-certificate-secret
                  key: client-certificate
            - name: RENKU_URL
              value: https://{{ .Values.global.renku.domain }}
            - name: RENKU_API_URL
              value: https://{{ .Values.global.renku.domain }}{{ .Values.knowledgeGraph.services.renku.resourcesPath }}
            - name: JENA_BASE_URL
              value: "http://{{ template "jena.fullname" . }}-master:{{ .Values.jena.service.port }}"
            - name: JENA_RENKU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "jena.fullname" . }}
                  key: jena-users-renku-password
            - name: TRIPLES_GENERATOR_BASE_URL
              value: "http://{{ template "triplesGenerator.fullname" . }}:{{ .Values.triplesGenerator.service.port }}"
            - name: TOKEN_REPOSITORY_BASE_URL
              value: "http://{{ template "tokenRepository.fullname" . }}:{{ .Values.tokenRepository.service.port }}"
            - name: EVENT_LOG_BASE_URL
              value: "http://{{ template "eventLog.fullname" . }}:{{ .Values.eventLog.service.port }}"
            - name: GITLAB_BASE_URL
              value: {{ .Values.gitlab.url }}
            - name: GITLAB_RATE_LIMIT
              value: {{ .Values.knowledgeGraph.gitlab.rateLimit }}
            - name: SENTRY_ENABLED
              value: "{{ .Values.sentry.enabled }}"
              {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
              value: {{ .Values.sentry.dsn }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry.environment }}
              {{- end }}
            - name: JAVA_OPTS
              value: -Xmx{{ .Values.knowledgeGraph.jvmXmx }} -XX:+UseG1GC
          ports:
            - name: http-kg
              containerPort: 9004
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http-kg
          readinessProbe:
            httpGet:
              path: /ping
              port: http-kg
          resources:
            {{- toYaml .Values.knowledgeGraph.resources | nindent 12 }}
          volumeMounts:
            {{- include "certificates.volumeMounts.javaCertsGeneral" . | nindent 12 }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
