apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowledgeGraph.fullname" . }}
  labels:
    app: {{ template "knowledgeGraph.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "knowledgeGraph.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "knowledgeGraph.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: knowledge-graph
          image: "{{ .Values.knowledgeGraph.image.repository }}:{{ .Values.knowledgeGraph.image.tag }}"
          imagePullPolicy: {{ .Values.knowledgeGraph.image.pullPolicy }}
          env:
            - name: RENKU_CLIENT_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: client-certificate-secret
                  key: client-certificate
            - name: RENKU_BASE_URL
              value: https://{{ .Values.global.renku.domain }}
            - name: RENKU_RESOURCES_URL
              value: https://{{ .Values.global.renku.domain }}{{ .Values.knowledgeGraph.services.renku.resourcesPath }}
            - name: JENA_DATASET_NAME
              {{- if .Values.global.graph.jena.dataset }}
              value: {{ .Values.global.graph.jena.dataset }}
              {{- else }}
              value: {{ .Release.Namespace }}
              {{- end }}
            - name: JENA_BASE_URL
              value: "http://{{ template "jena.fullname" . }}-master:{{ .Values.jena.service.port }}"
            - name: JENA_RENKU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jena.fullname" . }}
                  key: jena-renku-password
            - name: TOKEN_REPOSITORY_BASE_URL
              value: "http://{{ template "tokenRepository.fullname" . }}:{{ .Values.tokenRepository.service.port }}"
            - name: GITLAB_BASE_URL
              value: {{ .Values.gitlab.url }}
            - name: GITLAB_RATE_LIMIT
              value: {{ .Values.knowledgeGraph.gitlab.rateLimit }}
            - name: SENTRY_ENABLED
              value: "{{ .Values.sentry.enabled }}"
              {{- if .Values.sentry.enabled }}
            - name: SENTRY_BASE_URL
              value: {{ .Values.sentry.url }}
            - name: SENTRY_ENVIRONMENT_NAME
              value: {{ .Values.sentry.environmentName }}
              {{- end }}
            - name: THREADS_NUMBER
              value: "{{ .Values.knowledgeGraph.threadsNumber }}"
            - name: JAVA_OPTS
              value: -Xmx{{ .Values.knowledgeGraph.jvmXmx }} -XX:+UseG1GC
          ports:
            - name: http-kg
              containerPort: 9004
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http-kg
          readinessProbe:
            httpGet:
              path: /ping
              port: http-kg
          resources:
  {{- toYaml .Values.knowledgeGraph.resources | nindent 12 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
