apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graph.fullname" . }}
  labels:
    app: {{ template "graph.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  webhookService-hookToken-secret: {{ required "Fill in .Values.webhookService.hookToken.secret with `openssl rand -hex 8|base64`" .Values.webhookService.hookToken.secret | b64enc | quote }}
  tokenRepository-tokenEncryption-secret: {{ required "Fill in .Values.tokenRepository.tokenEncryption.secret with `openssl rand -hex 8|base64`" .Values.tokenRepository.tokenEncryption.secret | b64enc | quote }}
  tokenRepository-postgresPassword: {{ required "Fill in .Values.global.graph.tokenRepository.postgresPassword with `openssl rand -hex 16`" .Values.global.graph.tokenRepository.postgresPassword | b64enc | quote }}
