apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graph.fullname" . }}
  labels:
    app: {{ template "graph.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  triplesGenerator-play-secret: {{ required "Fill in .Values.triplesGenerator.play.secret with `sbt playGenerateSecret`" .Values.triplesGenerator.play.secret | b64enc | quote }}
  webhookService-play-secret: {{ required "Fill in .Values.webhookService.play.secret with `sbt playGenerateSecret`" .Values.webhookService.play.secret | b64enc | quote }}
  tokenRepository-token-secret: {{ required "Fill in .Values.tokenRepository.token.secret with `openssl rand -hex 8|base64`" .Values.tokenRepository.token.secret | b64enc | quote }}
  tokenRepository-dbPass: {{ required "Fill in .Values.tokenRepository.dbPass with `openssl rand -hex 16`" .Values.tokenRepository.dbPass | b64enc | quote }}
