apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graph.fullname" . }}
  labels:
    app: {{ template "graph.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  triplesGenerator-play-secret: {{ required "Fill in .Values.triplesGenerator.play.secret with `sbt playGenerateSecret`" .Values.triplesGenerator.play.secret | b64enc | quote }}
  webhookService-play-secret: {{ required "Fill in .Values.webhookService.play.secret with `sbt playGenerateSecret`" .Values.webhookService.play.secret | b64enc | quote }}
