apiVersion: v1
kind: Service
metadata:
  name: {{ include "tokenRepository.fullname" . }}
  labels:
    app: {{ template "tokenRepository.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.tokenRepository.service.type }}
  ports:
    - port: {{ .Values.tokenRepository.service.port }}
      targetPort: http-token-repo
      protocol: TCP
      name: http
  selector:
    app: {{ template "tokenRepository.name" . }}
    release: {{ .Release.Name }}
