apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "triplesGenerator.fullname" . }}
  labels:
    app: {{ template "triplesGenerator.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.triplesGenerator.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "triplesGenerator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "triplesGenerator.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
      containers:
        - name: triples-generator
          image: "{{ .Values.triplesGenerator.image.repository }}:{{ .Values.triplesGenerator.image.tag }}"
          imagePullPolicy: {{ .Values.triplesGenerator.image.pullPolicy }}
          env:
            - name: RENKU_CLIENT_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: client-certificate-secret
                  key: client-certificate
            - name: RENKU_DOMAIN
              value: {{ .Values.global.renku.domain }}
            - name: RENKU_BASE_URL
              value: https://{{ .Values.global.renku.domain }}
            - name: EVENT_LOG_BASE_URL
              value: "http://{{ template "eventLog.fullname" . }}:{{ .Values.eventLog.service.port }}"
            - name: TOKEN_REPOSITORY_BASE_URL
              value: "http://{{ template "tokenRepository.fullname" . }}:{{ .Values.tokenRepository.service.port }}"
            - name: GITLAB_BASE_URL
              value: {{ .Values.gitlab.url }}
            - name: GITLAB_RATE_LIMIT
              value: {{ .Values.triplesGenerator.gitlab.rateLimit }}
            - name: JENA_DATASET_NAME
              {{- if .Values.global.graph.jena.dataset }}
              value: {{ .Values.global.graph.jena.dataset }}
              {{- else }}
              value: {{ .Release.Namespace }}
             {{- end }}
            - name: JENA_BASE_URL
              value: "http://{{ template "jena.fullname" . }}-master:{{ .Values.jena.service.port }}"
            - name: JENA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jena.fullname" . }}
                  key: jena-admin-password
            - name: JENA_RENKU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jena.fullname" . }}
                  key: jena-renku-password
            - name: RENKU_DISABLE_VERSION_CHECK
              value: "true"
            - name: RE_PROVISIONING_REMOVAL_BATCH_SIZE
              value: "{{ .Values.triplesGenerator.reProvisioningRemovalBatchSize }}"
            - name: SENTRY_ENABLED
              value: "{{ .Values.sentry.enabled }}"
              {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
              value: {{ .Values.sentry.sentryDsnRenkuPython }}
            - name: SENTRY_GRAPH_DSN
              value: {{ .Values.sentry.dsn }}
            - name: SENTRY_ENV
              value: {{ .Values.sentry.environment }}
              {{- end }}
            - name: GENERATION_PROCESSES_NUMBER
              value: "{{ .Values.triplesGenerator.generationProcessesNumber }}"
            - name: TRANSFORMATION_PROCESSES_NUMBER
              value: "{{ .Values.triplesGenerator.transformationProcessesNumber }}"
            - name: JAVA_OPTS
              value: -Xmx{{ .Values.triplesGenerator.jvmXmx }} -XX:+UseG1GC
            - name: RENKU_PYTHON_DEV_VERSION
              value: "{{ .Values.triplesGenerator.renkuPythonDevVersion }}"
          ports:
            - name: http-triples-gn
              containerPort: 9002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http-triples-gn
            timeoutSeconds: 60
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 10
            {{- if .Values.triplesGenerator.renkuPythonDevVersion }}
            initialDelaySeconds: 120
            {{- end }}
          readinessProbe:
            httpGet:
              path: /ping
              port: http-triples-gn
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            {{- if .Values.triplesGenerator.renkuPythonDevVersion }}
            initialDelaySeconds: 120
            {{- end }}
          resources:
            {{- toYaml .Values.triplesGenerator.resources | nindent 12 }}
          volumeMounts:
            {{- include "certificates.volumeMounts.javaCertsGeneral" . | nindent 12 }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
