apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "triplesGenerator.fullname" . }}
  labels:
    app: {{ template "triplesGenerator.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "triplesGenerator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "triplesGenerator.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: triples-generator
          image: "{{ .Values.triplesGenerator.image.repository }}:{{ .Values.triplesGenerator.image.tag }}"
          imagePullPolicy: {{ .Values.triplesGenerator.image.pullPolicy }}
          env:
            - name: RENKU_DOMAIN
              value: {{ .Values.global.renku.domain }}
            - name: RENKU_BASE_URL
              value: https://{{ .Values.global.renku.domain }}
            - name: EVENT_LOG_BASE_URL
              value: "http://{{ template "eventLog.fullname" . }}:{{ .Values.eventLog.service.port }}"
            - name: TOKEN_REPOSITORY_BASE_URL
              value: "http://{{ template "tokenRepository.fullname" . }}:{{ .Values.tokenRepository.service.port }}"
            - name: GITLAB_BASE_URL
              value: {{ .Values.gitlab.url }}
            - name: GITLAB_RATE_LIMIT
              value: {{ .Values.triplesGenerator.gitlab.rateLimit }}
            - name: JENA_DATASET_NAME
              {{- if .Values.global.graph.jena.dataset }}
              value: {{ .Values.global.graph.jena.dataset }}
              {{- else }}
              value: {{ .Release.Namespace }}
             {{- end }}
            - name: JENA_BASE_URL
              value: "http://{{ template "jena.fullname" . }}:{{ .Values.jena.service.port }}"
            - name: JENA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jena.fullname" . }}
                  key: jena-admin-password
            - name: JENA_RENKU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "jena.fullname" . }}
                  key: jena-renku-password
            - name: RENKU_LOG_TIMEOUT
              value: "{{ .Values.triplesGenerator.renkuLogTimeout }}"
            - name: RE_PROVISIONING_INITIAL_DELAY
              value: "{{ .Values.triplesGenerator.reProvisioningInitialDelay }}"
            - name: SENTRY_DSN
              value: {{ .Values.sentry.sentryDsnRenkuPython }}
            - name: SENTRY_ENABLED
              value: "{{ .Values.sentry.enabled }}"
              {{- if .Values.sentry.enabled }}
            - name: SENTRY_BASE_URL
              value: {{ .Values.sentry.url }}
            - name: SENTRY_ENVIRONMENT_NAME
              value: {{ .Values.sentry.environmentName }}
              {{- end }}
            - name: GENERATION_PROCESSES_NUMBER
              value: "{{ .Values.triplesGenerator.generationProcessesNumber }}"
            - name: THREADS_NUMBER
              value: "{{ .Values.triplesGenerator.threadsNumber }}"
            - name: JAVA_OPTS
              value: -Xmx{{ .Values.triplesGenerator.jvmXmx }} -XX:+UseG1GC
          ports:
            - name: http-triples-gn
              containerPort: 9002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http-triples-gn
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: http-triples-gn
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
  {{ toYaml .Values.triplesGenerator.resources | indent 12 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
