apiVersion: v1
kind: Secret
metadata:
  name: {{ include "triplesGenerator.fullname" . }}
  labels:
    app: {{ template "triplesGenerator.name" . }}
    chart: {{ template "triplesGenerator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  dbEventLog-postgresPassword: {{ required "Fill in .Values.global.graph.dbEventLog.postgresPassword with `openssl rand -hex 16`" .Values.global.graph.dbEventLog.postgresPassword | b64enc | quote }}
