apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhookService.fullname" . }}
  labels:
    app: {{ template "webhookService.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  webhookService-hookToken-secret: {{ required "Fill in .Values.webhookService.hookToken.secret with `openssl rand -hex 8|base64`" .Values.webhookService.hookToken.secret | b64enc | quote }}
  dbEventLog-postgresPassword: {{ required "Fill in .Values.global.graph.dbEventLog.postgresPassword with `openssl rand -hex 16`" .Values.global.graph.dbEventLog.postgresPassword | b64enc | quote }}
