apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webhookService.fullname" . }}
  labels:
    app: {{ template "webhookService.name" . }}
    chart: {{ template "graph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "webhookService.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "webhookService.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
      containers:
        - name: webhook-service
          image: "{{ .Values.webhookService.image.repository }}:{{ .Values.webhookService.image.tag }}"
          imagePullPolicy: {{ .Values.webhookService.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: RENKU_CLIENT_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: client-certificate-secret
                  key: client-certificate
            - name: HOOK_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "webhookService.fullname" . }}
                  key: webhookService-hookToken-secret
            - name: EVENT_LOG_BASE_URL
              value: "http://{{ template "eventLog.fullname" . }}:{{ .Values.eventLog.service.port }}"
            - name: TOKEN_REPOSITORY_BASE_URL
              value: "http://{{ template "tokenRepository.fullname" . }}:{{ .Values.tokenRepository.service.port }}"
            - name: GITLAB_BASE_URL
              value: {{ .Values.gitlab.url }}
            - name: GITLAB_RATE_LIMIT
              value: {{ .Values.webhookService.gitlab.rateLimit }}
            - name: SELF_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SELF_URL
              {{- if .Values.global.renku.domain }}
              value: {{ template "http" . }}://{{ .Values.global.renku.domain }}
              {{- else }}
              value: {{ printf "http://$(SELF_IP):9001" | quote }}
              {{- end }}
            - name: SENTRY_ENABLED
              value: "{{ .Values.sentry.enabled }}"
              {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
              value: {{ .Values.sentry.dsn }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry.environment }}
              {{- end }}
            - name: JAVA_OPTS
              value: -Xmx{{ .Values.webhookService.jvmXmx }} -XX:+UseG1GC
          ports:
            - name: http-webhook-sv
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http-webhook-sv
          readinessProbe:
            httpGet:
              path: /ping
              port: http-webhook-sv
          resources:
            {{- toYaml .Values.webhookService.resources | nindent 12 }}
          volumeMounts:
            {{- include "certificates.volumeMounts.javaCertsGeneral" . | nindent 12 }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}
