branches:
  only:
  - master
language: scala
jdk: openjdk8
scala:
- 2.12.7
script:
- sbt ++$TRAVIS_SCALA_VERSION test && bash ./.travis/check-code-formatting.sh
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
