apiVersion: v1
appVersion: '1.0'
description: A Helm chart for renku graph services
name: renku-graph
# This is a dummy version just to satisfy GH action job. The real version is set during the release process.
version: 0.0.1
