dependencies:
- name: certificates
  version: "0.0.3"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
- name: renku-jena
  version: "0.0.19"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  alias: jena
