dependencies:
- name: certificates
  version: "0.0.2"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
- name: renku-jena
  version: "0.0.9"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  alias: jena