{
 "title": "Renku Event Log",
 "tags": [ "renku" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "kube_env_name", "label": "Env name", "query": "server_request_count" }
  ]
 },
 "panels": [
  {
   "title": "Event Log events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg by (status)(events_statuses_count{kubernetes_name=\"[[kube_env_name]]-event-log\"}), \"status\", \"$1\", \"status\", \"(.*)\")",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "avg(events_count{kubernetes_name=\"[[kube_env_name]]-event-log\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Top priority queued events",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(ceil(max by(project) (events_waiting_count{kubernetes_name=\"[[kube_env_name]]-event-log\"})), \"project\", \"$1\", \"project\", \"(.*)\")",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Events under processing",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(ceil(max by(project)(events_processing_count{kubernetes_name=\"[[kube_env_name]]-event-log\"})), \"project\", \"$1\", \"project\", \"(.*)\")",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "SQL queries times (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, rate(event_log_queries_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-event-log\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    }
   ]
  },
  {
   "title": "SQL queries times (50th percentile)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(0.5, rate(event_log_queries_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-event-log\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    }
   ]
  },
  {
   "title": "Events processing times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(events_processing_times_bucket{kubernetes_name=\"[[kube_env_name]]-triples-generator\"}[15m])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(events_processing_times_bucket{kubernetes_name=\"[[kube_env_name]]-triples-generator\"}[15m])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum(rate(events_statuses_count{kubernetes_name=\"[[kube_env_name]]-event-log\", status=\"TRIPLES_STORE\"}[15m]))",
     "legendFormat": "rate (events/second)"
    }
   ]
  },
  {
   "title": "Event Log Heap usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='[[kube_env_name]]-event-log'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='[[kube_env_name]]-event-log'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "label_replace(process_virtual_memory_bytes{kubernetes_name='[[kube_env_name]]-event-log'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Proc virt mem {{instance_label}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{kubernetes_name=\"[[kube_env_name]]-event-log\"}",
     "legendFormat": "classes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{kubernetes_name=\"[[kube_env_name]]-event-log\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_peak{kubernetes_name=\"[[kube_env_name]]-event-log\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "jvm_threads_daemon{kubernetes_name=\"[[kube_env_name]]-event-log\"}",
     "legendFormat": "deamon"
    }
   ]
  },
  {
   "title": "Thread state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{kubernetes_name=\"[[kube_env_name]]-event-log\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "GC collection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{kubernetes_name=\"[[kube_env_name]]-event-log\"}[2m])",
     "legendFormat": "{{gc}}"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{kubernetes_name=\"[[kube_env_name]]-event-log\"}[2m]) / rate(jvm_gc_collection_seconds_count{kubernetes_name=\"[[kube_env_name]]-event-log\"}[5m])",
     "legendFormat": "duration {{gc}}"
    }
   ]
  }
 ]
}