{
 "title": "Renku Knowledge Graph",
 "tags": [ "renku" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "kube_env_name", "label": "Env name", "query": "server_request_count" }
  ]
 },
 "panels": [
  {
   "title": "Number of entities by type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (entities)(entities_count{kubernetes_name=\"[[kube_env_name]]-knowledge-graph\"})",
     "legendFormat": "{{entities}}"
    }
   ]
  },
  {
   "title": "SparQL query times (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, rate(sparql_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-knowledge-graph\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    },
    {
     "expr": "max(histogram_quantile(0.95, rate(sparql_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-triples-generator\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    }
   ]
  },
  {
   "title": "SparQL query times (50th percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(0.5, rate(sparql_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-knowledge-graph\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    },
    {
     "expr": "max(histogram_quantile(0.5, rate(sparql_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-triples-generator\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    }
   ]
  }
 ]
}