{
 "title": "Knowledge Graph Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "kube_env_name", "label": "Env name", "query": { "query": "server_request_count_total" } },
   { "name": "env_namespace", "label": "Env namespace", "query": { "query": "server_request_count_total" } }
  ]
 },
 "panels": [
  {
   "title": "Messages throughput by type",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (category_mame)(rate(sent_events_count{namespace=\"${env_namespace}\"}[10m]))",
     "legendFormat": "{{category_name}}"
    }
   ]
  },
  {
   "title": "Awaiting generation events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"NEW\"}",
     "legendFormat": "NON_ERR"
    },
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"GENERATION_RECOVERABLE_FAILURE\"}",
     "legendFormat": "ERR"
    }
   ]
  },
  {
   "title": "Awaiting transformation events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"TRIPLES_GENERATED\"}",
     "legendFormat": "NON_ERR"
    },
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"TRANSFORMATION_RECOVERABLE_FAILURE\"}",
     "legendFormat": "ERR"
    }
   ]
  },
  {
   "title": "Under processing events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"GENERATING_TRIPLES\"}",
     "legendFormat": "GENERATING"
    },
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"TRANSFORMING_TRIPLES\"}",
     "legendFormat": "TRANSFORMING"
    }
   ]
  },
  {
   "title": "Triples store events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"TRIPLES_STORE\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Persistent failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"GENERATION_NON_RECOVERABLE_FAILURE\"}",
     "legendFormat": "GENERATION"
    },
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"TRANSFORMATION_NON_RECOVERABLE_FAILURE\"}",
     "legendFormat": "TRANSFORMATION"
    }
   ]
  },
  {
   "title": "Deletions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"AWAITING_DELETION\"}",
     "legendFormat": "AWAITING"
    },
    {
     "expr": "events_statuses_count{service=\"${kube_env_name}-event-log\", status=\"DELETING\"}",
     "legendFormat": "DELETING"
    }
   ]
  },
  {
   "title": "Events summary",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(events_count{service=\"${kube_env_name}-event-log\", namespace=\"${env_namespace}\"})",
     "legendFormat": "All"
    },
    {
     "expr": "(\nscalar(avg by (status)(events_statuses_count{service=\"[[kube_env_name]]-event-log\", namespace=\"[[env_namespace]]\", status=\"GENERATION_NON_RECOVERABLE_FAILURE\"})) +\nscalar(avg by (status)(events_statuses_count{service=\"[[kube_env_name]]-event-log\", namespace=\"[[env_namespace]]\", status=\"TRANSFORMATION_NON_RECOVERABLE_FAILURE\"}))\n) / (\nscalar(avg by (status)(events_statuses_count{service=\"[[kube_env_name]]-event-log\", namespace=\"[[env_namespace]]\", status=\"TRIPLES_STORE\"})) + \nscalar(avg by (status)(events_statuses_count{service=\"[[kube_env_name]]-event-log\", namespace=\"[[env_namespace]]\", status=\"GENERATION_NON_RECOVERABLE_FAILURE\"})) + scalar(avg by (status)(events_statuses_count{service=\"[[kube_env_name]]-event-log\", namespace=\"[[env_namespace]]\", status=\"TRANSFORMATION_NON_RECOVERABLE_FAILURE\"}))\n)",
     "legendFormat": "Failure Rate"
    }
   ]
  },
  {
   "title": "Number of errors by service",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(app)(count_over_time({app=~\"event-log|triples-generator|webhook-service|knowledge-graph|commit-event-service|token-repository\", namespace=\"$env_namespace\"} |= \"ERROR\"[10m]))",
     "legendFormat": "{{app}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Synchronization messages queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(avg by (category_name)(category_name_events_count{service=\"${kube_env_name}-event-log\", namespace=\"${env_namespace}\"}), \"category_name\", \"$1\", \"category_name\", \"(.*)\")",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Events processing times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(triples_generation_processing_times_bucket{service=\"${kube_env_name}-triples-generator\"}[15m])) by (le))",
     "legendFormat": "Triples generation - 95th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(triples_generation_processing_times_bucket{service=\"${kube_env_name}-triples-generator\", namespace=\"${env_namespace}\"}[15m])) by (le))",
     "legendFormat": "Triples generation - 50th percentile"
    },
    {
     "expr": "sum(rate(events_statuses_count{service=\"${kube_env_name}-event-log\", namespace=\"${env_namespace}\", status=\"TRIPLES_STORE\"}[15m]))",
     "legendFormat": "rate (events/second)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(triples_transformation_processing_times_bucket{service=\"${kube_env_name}-triples-generator\", namespace=\"${env_namespace}\"}[15m])) by (le))",
     "legendFormat": "Triples transformation - 95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(triples_transformation_processing_times_bucket{service=\"${kube_env_name}-triples-generator\", namespace=\"${env_namespace}\"}[15m])) by (le))",
     "legendFormat": "Triples transformation - 50th percentile"
    }
   ]
  }
 ]
}