{
 "title": "Graph Services response times",
 "tags": [ "renku" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "kube_env_name", "label": "Env name", "query": { "query": "server_request_count_total" } },
   { "name": "env_namespace", "label": "Env namespace", "query": { "query": "server_request_count_total" } }
  ]
 },
 "panels": [
  {
   "title": "Knowledge Graph response times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"${kube_env_name}-knowledge-graph\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count_total{kubernetes_name=\"${kube_env_name}-knowledge-graph\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Webhook Service response times",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"${kube_env_name}-webhook-service\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count_total{kubernetes_name=\"${kube_env_name}-webhook-service\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Commit Event Service response times",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"${kube_env_name}-commit-event-service\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count_total{kubernetes_name=\"${kube_env_name}-commit-event-service\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Event Log response times",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"${kube_env_name}-event-log\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"${kube_env_name}-event-log\"}[5m])) by (le))",
     "legendFormat": "50th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count_total{kubernetes_name=\"${kube_env_name}-event-log\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Triples Generator response times",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"${kube_env_name}-triples-generator\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count_total{kubernetes_name=\"${kube_env_name}-triples-generator\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Token Repository response times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"${kube_env_name}-token-repository\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count_total{kubernetes_name=\"${kube_env_name}-token-repository\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "GitLab response times by API",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, rate(gitlab_api_calls_bucket{kubernetes_namespace=\"${env_namespace}\"}[5m]))) by (call_id)",
     "legendFormat": "{{call_id}}"
    }
   ]
  },
  {
   "title": "GitLab calls throughput by API",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (call_id) (rate(gitlab_api_calls_bucket{kubernetes_namespace=\"${env_namespace}\"}[5m])), \"call_id\", \"$1\", \"call_id\", \"(.*)\")",
     "legendFormat": "{{call_id}} req/sec"
    }
   ]
  }
 ]
}