{
 "title": "Graph Services response statuses",
 "tags": [ "renku" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "kube_env_name", "label": "Env name", "query": "server_request_count" }
  ]
 },
 "panels": [
  {
   "title": "Knowledge Graph response statuses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (status) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-knowledge-graph\"}[5m])), \"status\", \"$1\", \"status\", \"(.*)\")",
     "legendFormat": "{{status}}/sec"
    }
   ]
  },
  {
   "title": "Webhook Service response statuses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (status) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-webhook-service\"}[5m])), \"status\", \"$1\", \"status\", \"(.*)\")",
     "legendFormat": "{{status}}/sec"
    }
   ]
  },
  {
   "title": "Event Log response statuses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (status) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-event-log\"}[5m])), \"status\", \"$1\", \"status\", \"(.*)\")",
     "legendFormat": "{{status}}/sec"
    }
   ]
  },
  {
   "title": "Triples Generator response statuses",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (status) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-triples-generator\"}[5m])), \"status\", \"$1\", \"status\", \"(.*)\")",
     "legendFormat": "{{status}}/sec"
    }
   ]
  },
  {
   "title": "Token Repository response statuses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by (status) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-token-repository\"}[5m])), \"status\", \"$1\", \"status\", \"(.*)\")",
     "legendFormat": "{{status}}/sec"
    }
   ]
  }
 ]
}