{
 "title": "Graph Services memory",
 "tags": [ "renku" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "kube_env_name", "label": "Env name", "query": "server_request_count" }
  ]
 },
 "panels": [
  {
   "title": "Knowledge Graph memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='[[kube_env_name]]-knowledge-graph'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='[[kube_env_name]]-knowledge-graph'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "label_replace(process_virtual_memory_bytes{kubernetes_name='[[kube_env_name]]-knowledge-graph'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Proc virt mem {{instance_label}}"
    }
   ]
  },
  {
   "title": "Webhook Service memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='[[kube_env_name]]-webhook-service'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='[[kube_env_name]]-webhook-service'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "label_replace(process_virtual_memory_bytes{kubernetes_name='[[kube_env_name]]-webhook-service'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Proc virt mem {{instance_label}}"
    }
   ]
  },
  {
   "title": "Commit Event Service memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='[[kube_env_name]]-commit-event-service'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='[[kube_env_name]]-commit-event-service'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "label_replace(process_virtual_memory_bytes{kubernetes_name='[[kube_env_name]]-commit-event-service'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Proc virt mem {{instance_label}}"
    }
   ]
  },
  {
   "title": "Event Log memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='[[kube_env_name]]-event-log'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='[[kube_env_name]]-event-log'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "label_replace(process_virtual_memory_bytes{kubernetes_name='[[kube_env_name]]-event-log'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Proc virt mem {{instance_label}}"
    }
   ]
  },
  {
   "title": "Triples Generator memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='[[kube_env_name]]-triples-generator'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='[[kube_env_name]]-triples-generator'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "label_replace(process_virtual_memory_bytes{kubernetes_name='[[kube_env_name]]-triples-generator'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Proc virt mem {{instance_label}}"
    }
   ]
  },
  {
   "title": "Token Repository memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='[[kube_env_name]]-token-repository'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='[[kube_env_name]]-token-repository'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "label_replace(process_virtual_memory_bytes{kubernetes_name='[[kube_env_name]]-token-repository'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Proc virt mem {{instance_label}}"
    }
   ]
  }
 ]
}