{
 "title": "Graph Services memory & cpu",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "kube_env_name", "label": "Env name", "query": { "query": "server_request_count_total" } },
   { "name": "env_namespace", "label": "Env namespace", "query": { "query": "server_request_count_total" } }
  ]
 },
 "panels": [
  {
   "title": "Knowledge Graph memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='${kube_env_name}-knowledge-graph'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='${kube_env_name}-knowledge-graph'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container!=\"POD\", namespace=\"${env_namespace}\", container=\"knowledge-graph\"}",
     "legendFormat": "Container"
    }
   ]
  },
  {
   "title": "Knowledge Graph cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"knowledge-graph\"}[5m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"knowledge-graph\"}[5m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"knowledge-graph\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Webhook Service memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='${kube_env_name}-webhook-service'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='${kube_env_name}-webhook-service', kubernetes_namespace=\"${env_namespace}\"}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container!=\"POD\", namespace='${env_namespace}', container=\"webhook-service\"}",
     "legendFormat": "Container"
    }
   ]
  },
  {
   "title": "Webhook Service cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"webhook-service\"}[5m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"webhook-service\"}[5m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"webhook-service\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Commit Event Service memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='${kube_env_name}-commit-event-service'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='${kube_env_name}-commit-event-service'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container!=\"POD\", namespace=\"${env_namespace}\", container=\"commit-event-service\"}",
     "legendFormat": "Container"
    }
   ]
  },
  {
   "title": "Commit Event Service cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"commit-event-service\"}[5m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"commit-event-service\"}[5m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"commit-event-service\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Event Log memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='${kube_env_name}-event-log'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='${kube_env_name}-event-log'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container!=\"POD\", namespace=\"${env_namespace}\", container=\"event-log\"}",
     "legendFormat": "Container"
    }
   ]
  },
  {
   "title": "Event Log cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"event-log\"}[5m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"event-log\"}[5m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"event-log\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Triples Generator memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='${kube_env_name}-triples-generator'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='${kube_env_name}-triples-generator'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container!=\"POD\", namespace=\"${env_namespace}\", container=\"triples-generator\"}",
     "legendFormat": "Container {{pod}}"
    }
   ]
  },
  {
   "title": "Triples Generator cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"triples-generator\"}[5m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"triples-generator\"}[5m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"triples-generator\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Token Repository memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='${kube_env_name}-token-repository'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used {{instance_label}}"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_max{area='heap', kubernetes_name='${kube_env_name}-token-repository'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap max {{instance_label}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container!=\"POD\", namespace=\"${env_namespace}\", container=\"token-repository\"}",
     "legendFormat": "Container"
    }
   ]
  },
  {
   "title": "Token Repository cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"token-repository\"}[5m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"token-repository\"}[5m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"token-repository\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Jena memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container!=\"POD\", namespace=\"${env_namespace}\", container=\"jena\"}",
     "legendFormat": "Container"
    },
    {
     "expr": "label_replace(jvm_memory_bytes_used{area='heap', kubernetes_name='${kube_env_name}-jena'}, \"instance_label\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "Heap used"
    }
   ]
  },
  {
   "title": "Jena cpu",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"jena\"}[5m])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"jena\"}[5m])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\", namespace=\"${env_namespace}\", container=\"jena\"}[5m])",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}