{
 "title": "Graph Services response times",
 "tags": [ "renku" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "kube_env_name", "label": "Env name", "query": "server_request_count" }
  ]
 },
 "panels": [
  {
   "title": "Knowledge Graph response times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"[[kube_env_name]]-knowledge-graph\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-knowledge-graph\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Webhook Service response times",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"[[kube_env_name]]-webhook-service\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-webhook-service\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Commit Event Service response times",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"[[kube_env_name]]-commit-event-service\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-commit-event-service\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Event Log response times",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"[[kube_env_name]]-event-log\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-event-log\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Triples Generator response times",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"[[kube_env_name]]-triples-generator\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-triples-generator\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  },
  {
   "title": "Token Repository response times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_response_duration_seconds_bucket{kubernetes_name=\"[[kube_env_name]]-token-repository\"}[5m])) by (le))",
     "legendFormat": "95th percentile of processing times"
    },
    {
     "expr": "label_replace(sum by (method) (rate(server_request_count{kubernetes_name=\"[[kube_env_name]]-token-repository\"}[5m])), \"method\", \"$1\", \"method\", \"(.*)\")",
     "legendFormat": "{{method}} req/sec"
    }
   ]
  }
 ]
}