{
 "title": "Renku Graph SQL execution times",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "kube_env_name", "label": "Env name", "query": { "query": "server_request_count_total" } },
   { "name": "env_namespace", "label": "Env namespace", "query": { "query": "server_request_count_total" } }
  ]
 },
 "panels": [
  {
   "title": "Event Log - 95th percentile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, rate(event_log_queries_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-event-log\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    }
   ]
  },
  {
   "title": "Event Log - 50th percentile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(0.5, rate(event_log_queries_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-event-log\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    }
   ]
  },
  {
   "title": "Token Repository - 95th percentile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(0.95, rate(token_repository_queries_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-token-repository\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    }
   ]
  },
  {
   "title": "Token Repository - 50th percentile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(0.5, rate(token_repository_queries_execution_times_bucket{kubernetes_name=\"[[kube_env_name]]-token-repository\"}[5m]))) by (query_id)",
     "legendFormat": "{{query_id}}"
    }
   ]
  }
 ]
}