apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "triples-generator.fullname" . }}
  labels:
    app: {{ template "triples-generator.name" . }}
    chart: {{ template "triples-generator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "triples-generator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "triples-generator.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PLAY_APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "triples-generator.fullname" . }}
                  key: triplesGenerator-play-secret
            - name: GITLAB_BASE_URL
              value: {{ .Values.triplesGenerator.gitlab.url }}
            - name: JENA_BASE_URL
              value: {{ .Values.triplesGenerator.jena.url }}
            - name: JENA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "triples-generator.fullname" . }}
                  key: jena-admin-password
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
