apiVersion: v1
kind: Secret
metadata:
  name: {{ include "triples-generator.fullname" . }}
  labels:
    app: {{ template "triples-generator.name" . }}
    chart: {{ template "triples-generator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  triplesGenerator-play-secret: {{ required "Fill in .Values.triplesGenerator.play.secret with `sbt playGenerateSecret`" .Values.triplesGenerator.play.secret | b64enc | quote }}
  jena-admin-password: {{ required "Fill in .Values.jena.admin.password with `openssl rand -hex 16`" .Values.jena.admin.password | b64enc | quote }}
