apiVersion: v1
kind: Service
metadata:
  name: {{ include "graph-services.fullname" . }}-webhook-service
  labels:
    app: {{ template "graph-services.name" . }}
    chart: {{ template "graph-services.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.webhookService.service.type }}
  ports:
    - port: {{ .Values.webhookService.service.port }}
      targetPort: http2
      protocol: TCP
      name: http
  selector:
    app: {{ template "graph-services.name" . }}
    release: {{ .Release.Name }}
