name: release
on:
  pull_request:
    branches:
     - ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name:  
    - run: |
      git config --global user.name "RenkuBot"
      git config --global user.email "renku@datascience.ch"
      git config credential.helper "store --file=.git/credentials"
      echo "https://${GITHUB_TOKEN}:@github.com" >.git/credentials  
    - name: Create release
      run: sbt "release skip-tests default-tag-exists-answer k with-defaults"
