name: Test PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
env:
  SCALA_VERSION: "2.13.2"
  SBT_OPTS: "-XX:+CMSClassUnloadingEnabled -Xmx1G"
jobs:
  cleanup-previous-runs:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  test:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    needs: [cleanup-previous-runs]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Unit test
        env:

        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean test
  acceptance-test:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    needs: [ cleanup-previous-runs ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Acceptance tests
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project acceptance-tests" clean test
  formatter:
      runs-on: ubuntu-latest
      if: github.event.action != 'closed'
      needs: [ cleanup-previous-runs ]
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
        - name: Format
          run: sbt scalafmtCheck

