name: Deploy and Test PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  cleanup-previous-runs:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  test-pr:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    needs: [cleanup-previous-runs]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Test and format
        env:
          SBT_OPTS: "-XX:+CMSClassUnloadingEnabled -Xmx1G"
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean test && sbt -Dsbt.color=always -Dsbt.supershell=false "project acceptance-tests" clean test && sbt scalafmtCheck

