name: test
on:
  pull_request:
    branches:
     - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure github
      run: |
        git config --global user.name "RenkuBot"
        git config --global user.email "renku@datascience.ch"
        git config credential.helper "store --file=.git/credentials"
        echo "https://${GITHUB_TOKEN}:@github.com" >.git/credentials